import { Jobseeker, Employer, ActiveJob, Application, PremiumOrder, PremiumService } from './admin-types';

export const mockJobseekers: Jobseeker[] = [
  { 
    id: 'JS001', 
    fullName: 'John Smith', 
    emailAddress: 'john.smith@email.com', 
    phoneNumber: '+1-555-0123',
    location: 'New York, NY',
    nationality: 'American',
    currentRole: 'Senior Software Engineer',
    company: 'TechCorp Solutions',
    yearsOfExperience: 8,
    industry: 'Technology',
    profileUrl: '/candidate/JS001',
    status: 'active'
  },
  { 
    id: 'JS002', 
    fullName: 'Sarah Johnson', 
    emailAddress: 'sarah.j@email.com', 
    phoneNumber: '+1-555-0124',
    location: 'San Francisco, CA',
    nationality: 'American',
    currentRole: 'Product Manager',
    company: 'InnovateLabs',
    yearsOfExperience: 6,
    industry: 'Technology',
    profileUrl: '/candidate/JS002',
    status: 'active'
  },
  { 
    id: 'JS003', 
    fullName: 'Michael Brown', 
    emailAddress: 'm.brown@email.com', 
    phoneNumber: '+1-555-0125',
    location: 'Chicago, IL',
    nationality: 'American',
    currentRole: 'UX Designer',
    company: 'Global Dynamics',
    yearsOfExperience: 4,
    industry: 'Design',
    profileUrl: '/candidate/JS003',
    status: 'blocked'
  },
  { 
    id: 'JS004', 
    fullName: 'Emily Davis', 
    emailAddress: 'emily.davis@email.com', 
    phoneNumber: '+1-555-0126',
    location: 'Austin, TX',
    nationality: 'American',
    currentRole: 'Data Scientist',
    company: 'StartupHub',
    yearsOfExperience: 5,
    industry: 'Data Science',
    profileUrl: '/candidate/JS004',
    status: 'active'
  },
  { 
    id: 'JS005', 
    fullName: 'David Wilson', 
    emailAddress: 'd.wilson@email.com', 
    phoneNumber: '+1-555-0127',
    location: 'Seattle, WA',
    nationality: 'American',
    currentRole: 'Marketing Specialist',
    company: 'Enterprise Systems',
    yearsOfExperience: 7,
    industry: 'Marketing',
    profileUrl: '/candidate/JS005',
    status: 'active'
  },
  { 
    id: 'JS006', 
    fullName: 'Lisa Anderson', 
    emailAddress: 'lisa.anderson@email.com', 
    phoneNumber: '+1-555-0128',
    location: 'Boston, MA',
    nationality: 'American',
    currentRole: 'DevOps Engineer',
    company: 'Digital Innovations',
    yearsOfExperience: 6,
    industry: 'Technology',
    profileUrl: '/candidate/JS006',
    status: 'active'
  },
  { 
    id: 'JS007', 
    fullName: 'Robert Taylor', 
    emailAddress: 'robert.t@email.com', 
    phoneNumber: '+1-555-0129',
    location: 'Denver, CO',
    nationality: 'American',
    currentRole: 'Sales Representative',
    company: 'FutureTech',
    yearsOfExperience: 3,
    industry: 'Sales',
    profileUrl: '/candidate/JS007',
    status: 'blocked'
  },
  { 
    id: 'JS008', 
    fullName: 'Jennifer Martinez', 
    emailAddress: 'j.martinez@email.com', 
    phoneNumber: '+1-555-0130',
    location: 'Miami, FL',
    nationality: 'American',
    currentRole: 'Frontend Developer',
    company: 'CloudFirst',
    yearsOfExperience: 4,
    industry: 'Technology',
    profileUrl: '/candidate/JS008',
    status: 'active'
  },
  { 
    id: 'JS009', 
    fullName: 'Christopher Lee', 
    emailAddress: 'chris.lee@email.com', 
    phoneNumber: '+1-555-0131',
    location: 'Portland, OR',
    nationality: 'American',
    currentRole: 'HR Manager',
    company: 'DataDriven Inc',
    yearsOfExperience: 8,
    industry: 'Human Resources',
    profileUrl: '/candidate/JS009',
    status: 'active'
  },
  { 
    id: 'JS010', 
    fullName: 'Amanda Garcia', 
    emailAddress: 'amanda.g@email.com', 
    phoneNumber: '+1-555-0132',
    location: 'Phoenix, AZ',
    nationality: 'American',
    currentRole: 'Business Analyst',
    company: 'NextGen Solutions',
    yearsOfExperience: 5,
    industry: 'Business',
    profileUrl: '/candidate/JS010',
    status: 'active'
  },
];

export const mockEmployers: Employer[] = [
  { 
    id: 'EMP001', 
    companyName: 'TechCorp Solutions', 
    companyEmail: 'hr@techcorp.com', 
    phoneNumber: '+1-555-1001',
    website: 'https://techcorp.com',
    industry: 'Technology',
    teamSize: '500-1000',
    foundedYear: 2010,
    profileUrl: '/employer/profile/EMP001',
    status: 'active'
  },
  { 
    id: 'EMP002', 
    companyName: 'InnovateLabs', 
    companyEmail: 'careers@innovatelabs.com', 
    phoneNumber: '+1-555-1002',
    website: 'https://innovatelabs.com',
    industry: 'Technology',
    teamSize: '50-100',
    foundedYear: 2018,
    profileUrl: '/employer/profile/EMP002',
    status: 'active'
  },
  { 
    id: 'EMP003', 
    companyName: 'Global Dynamics', 
    companyEmail: 'jobs@globaldynamics.com', 
    phoneNumber: '+1-555-1003',
    website: 'https://globaldynamics.com',
    industry: 'Consulting',
    teamSize: '200-500',
    foundedYear: 2005,
    profileUrl: '/employer/profile/EMP003',
    status: 'blocked'
  },
  { 
    id: 'EMP004', 
    companyName: 'StartupHub', 
    companyEmail: 'team@startuphub.com', 
    phoneNumber: '+1-555-1004',
    website: 'https://startuphub.com',
    industry: 'Technology',
    teamSize: '10-50',
    foundedYear: 2020,
    profileUrl: '/employer/profile/EMP004',
    status: 'active'
  },
  { 
    id: 'EMP005', 
    companyName: 'Enterprise Systems', 
    companyEmail: 'hr@enterprisesys.com', 
    phoneNumber: '+1-555-1005',
    website: 'https://enterprisesys.com',
    industry: 'Technology',
    teamSize: '1000+',
    foundedYear: 1995,
    profileUrl: '/employer/profile/EMP005',
    status: 'active'
  },
  { 
    id: 'EMP006', 
    companyName: 'Digital Innovations', 
    companyEmail: 'careers@digitalinnovations.com', 
    phoneNumber: '+1-555-1006',
    website: 'https://digitalinnovations.com',
    industry: 'Technology',
    teamSize: '100-200',
    foundedYear: 2015,
    profileUrl: '/employer/profile/EMP006',
    status: 'active'
  },
  { 
    id: 'EMP007', 
    companyName: 'FutureTech', 
    companyEmail: 'jobs@futuretech.com', 
    phoneNumber: '+1-555-1007',
    website: 'https://futuretech.com',
    industry: 'Technology',
    teamSize: '50-100',
    foundedYear: 2019,
    profileUrl: '/employer/profile/EMP007',
    status: 'active'
  },
  { 
    id: 'EMP008', 
    companyName: 'CloudFirst', 
    companyEmail: 'hr@cloudfirst.com', 
    phoneNumber: '+1-555-1008',
    website: 'https://cloudfirst.com',
    industry: 'Cloud Services',
    teamSize: '200-500',
    foundedYear: 2012,
    profileUrl: '/employer/profile/EMP008',
    status: 'active'
  },
  { 
    id: 'EMP009', 
    companyName: 'DataDriven Inc', 
    companyEmail: 'careers@datadriven.com', 
    phoneNumber: '+1-555-1009',
    website: 'https://datadriven.com',
    industry: 'Data Analytics',
    teamSize: '100-200',
    foundedYear: 2016,
    profileUrl: '/employer/profile/EMP009',
    status: 'active'
  },
  { 
    id: 'EMP010', 
    companyName: 'NextGen Solutions', 
    companyEmail: 'jobs@nextgen.com', 
    phoneNumber: '+1-555-1010',
    website: 'https://nextgen.com',
    industry: 'Technology',
    teamSize: '50-100',
    foundedYear: 2021,
    profileUrl: '/employer/profile/EMP010',
    status: 'active'
  },
];

export const mockActiveJobs: ActiveJob[] = [
  { 
    id: 'JOB001', 
    jobTitle: 'Senior Software Engineer', 
    companyName: 'TechCorp Solutions',
    location: 'New York, NY',
    jobType: 'Full-time',
    minimumSalary: 120000,
    maximumSalary: 180000,
    applicationDeadline: '2024-02-15',
    status: 'active',
    jobUrl: '/employer/active-jobs/senior-software-engineer'
  },
  { 
    id: 'JOB002', 
    jobTitle: 'Product Manager', 
    companyName: 'InnovateLabs',
    location: 'San Francisco, CA',
    jobType: 'Full-time',
    minimumSalary: 130000,
    maximumSalary: 200000,
    applicationDeadline: '2024-02-14',
    status: 'active',
    jobUrl: '/employer/active-jobs/product-manager'
  },
  { 
    id: 'JOB003', 
    jobTitle: 'UX Designer', 
    companyName: 'Global Dynamics',
    location: 'Chicago, IL',
    jobType: 'Full-time',
    minimumSalary: 80000,
    maximumSalary: 120000,
    applicationDeadline: '2024-02-13',
    status: 'active',
    jobUrl: '/employer/active-jobs/ux-designer'
  },
  { 
    id: 'JOB004', 
    jobTitle: 'Data Scientist', 
    companyName: 'StartupHub',
    location: 'Austin, TX',
    jobType: 'Full-time',
    minimumSalary: 100000,
    maximumSalary: 150000,
    applicationDeadline: '2024-02-12',
    status: 'active',
    jobUrl: '/employer/active-jobs/data-scientist'
  },
  { 
    id: 'JOB005', 
    jobTitle: 'Marketing Specialist', 
    companyName: 'Enterprise Systems',
    location: 'Seattle, WA',
    jobType: 'Full-time',
    minimumSalary: 70000,
    maximumSalary: 100000,
    applicationDeadline: '2024-02-11',
    status: 'active',
    jobUrl: '/employer/active-jobs/marketing-specialist'
  },
  { 
    id: 'JOB006', 
    jobTitle: 'DevOps Engineer', 
    companyName: 'Digital Innovations',
    location: 'Boston, MA',
    jobType: 'Full-time',
    minimumSalary: 110000,
    maximumSalary: 160000,
    applicationDeadline: '2024-02-10',
    status: 'active',
    jobUrl: '/employer/active-jobs/devops-engineer'
  },
  { 
    id: 'JOB007', 
    jobTitle: 'Sales Representative', 
    companyName: 'FutureTech',
    location: 'Denver, CO',
    jobType: 'Full-time',
    minimumSalary: 60000,
    maximumSalary: 90000,
    applicationDeadline: '2024-02-09',
    status: 'active',
    jobUrl: '/employer/active-jobs/sales-representative'
  },
  { 
    id: 'JOB008', 
    jobTitle: 'Frontend Developer', 
    companyName: 'CloudFirst',
    location: 'Miami, FL',
    jobType: 'Full-time',
    minimumSalary: 90000,
    maximumSalary: 130000,
    applicationDeadline: '2024-02-08',
    status: 'active',
    jobUrl: '/employer/active-jobs/frontend-developer'
  },
  { 
    id: 'JOB009', 
    jobTitle: 'HR Manager', 
    companyName: 'DataDriven Inc',
    location: 'Portland, OR',
    jobType: 'Full-time',
    minimumSalary: 80000,
    maximumSalary: 120000,
    applicationDeadline: '2024-02-07',
    status: 'active',
    jobUrl: '/employer/active-jobs/hr-manager'
  },
  { 
    id: 'JOB010', 
    jobTitle: 'Business Analyst', 
    companyName: 'NextGen Solutions',
    location: 'Phoenix, AZ',
    jobType: 'Full-time',
    minimumSalary: 75000,
    maximumSalary: 110000,
    applicationDeadline: '2024-02-06',
    status: 'active',
    jobUrl: '/employer/active-jobs/business-analyst'
  },
];

export const mockApplications: Application[] = [
  { id: 'APP001', candidate: 'John Smith', jobTitle: 'Senior Software Engineer', applicationUrl: '/employer/applicants/john-smith' },
  { id: 'APP002', candidate: 'Sarah Johnson', jobTitle: 'Product Manager', applicationUrl: '/employer/applicants/sarah-johnson' },
  { id: 'APP003', candidate: 'Michael Brown', jobTitle: 'UX Designer', applicationUrl: '/employer/applicants/michael-brown' },
  { id: 'APP004', candidate: 'Emily Davis', jobTitle: 'Data Scientist', applicationUrl: '/employer/applicants/emily-davis' },
  { id: 'APP005', candidate: 'David Wilson', jobTitle: 'Marketing Specialist', applicationUrl: '/employer/applicants/david-wilson' },
  { id: 'APP006', candidate: 'Lisa Anderson', jobTitle: 'DevOps Engineer', applicationUrl: '/employer/applicants/lisa-anderson' },
  { id: 'APP007', candidate: 'Robert Taylor', jobTitle: 'Sales Representative', applicationUrl: '/employer/applicants/robert-taylor' },
  { id: 'APP008', candidate: 'Jennifer Martinez', jobTitle: 'Frontend Developer', applicationUrl: '/employer/applicants/jennifer-martinez' },
  { id: 'APP009', candidate: 'Christopher Lee', jobTitle: 'HR Manager', applicationUrl: '/employer/applicants/christopher-lee' },
  { id: 'APP010', candidate: 'Amanda Garcia', jobTitle: 'Business Analyst', applicationUrl: '/employer/applicants/amanda-garcia' },
];

export const mockPremiumOrders: PremiumOrder[] = [
  { 
    id: 'ORD001', 
    buyerName: 'TechCorp Solutions', 
    startDate: '2024-01-15', 
    expiryDate: '2024-07-15',
    status: 'active',
    amount: 299.99, 
    orderUrl: '/admin/orders/ORD001' 
  },
  { 
    id: 'ORD002', 
    buyerName: 'John Smith', 
    startDate: '2024-01-14', 
    expiryDate: '2024-04-14',
    status: 'active',
    amount: 99.99, 
    orderUrl: '/admin/orders/ORD002' 
  },
  { 
    id: 'ORD003', 
    buyerName: 'InnovateLabs', 
    startDate: '2024-01-13', 
    expiryDate: '2024-07-13',
    status: 'active',
    amount: 499.99, 
    orderUrl: '/admin/orders/ORD003' 
  },
  { 
    id: 'ORD004', 
    buyerName: 'Sarah Johnson', 
    startDate: '2024-01-12', 
    expiryDate: '2024-04-12',
    status: 'active',
    amount: 149.99, 
    orderUrl: '/admin/orders/ORD004' 
  },
  { 
    id: 'ORD005', 
    buyerName: 'Global Dynamics', 
    startDate: '2024-01-11', 
    expiryDate: '2024-07-11',
    status: 'active',
    amount: 799.99, 
    orderUrl: '/admin/orders/ORD005' 
  },
  { 
    id: 'ORD006', 
    buyerName: 'Michael Brown', 
    startDate: '2024-01-10', 
    expiryDate: '2024-04-10',
    status: 'active',
    amount: 199.99, 
    orderUrl: '/admin/orders/ORD006' 
  },
  { 
    id: 'ORD007', 
    buyerName: 'StartupHub', 
    startDate: '2024-01-09', 
    expiryDate: '2024-07-09',
    status: 'active',
    amount: 399.99, 
    orderUrl: '/admin/orders/ORD007' 
  },
  { 
    id: 'ORD008', 
    buyerName: 'Emily Davis', 
    startDate: '2024-01-08', 
    expiryDate: '2024-04-08',
    status: 'active',
    amount: 99.99, 
    orderUrl: '/admin/orders/ORD008' 
  },
  { 
    id: 'ORD009', 
    buyerName: 'Enterprise Systems', 
    startDate: '2024-01-07', 
    expiryDate: '2024-07-07',
    status: 'active',
    amount: 599.99, 
    orderUrl: '/admin/orders/ORD009' 
  },
  { 
    id: 'ORD010', 
    buyerName: 'David Wilson', 
    startDate: '2024-01-06', 
    expiryDate: '2024-04-06',
    status: 'active',
    amount: 249.99, 
    orderUrl: '/admin/orders/ORD010' 
  },
];

export const mockPremiumServices: PremiumService[] = [
  // Jobseeker Services
  {
    id: 'SVC001',
    buyerName: 'John Smith',
    buyerType: 'jobseeker',
    serviceName: 'Premium Profile Boost',
    serviceType: 'Profile Enhancement',
    orderDate: '2024-01-15',
    status: 'active',
    amount: 49.99,
    description: 'Enhanced profile visibility and priority listing',
    orderUrl: '/admin/services/SVC001'
  },
  {
    id: 'SVC002',
    buyerName: 'Sarah Johnson',
    buyerType: 'jobseeker',
    serviceName: 'Resume Review Service',
    serviceType: 'Career Services',
    orderDate: '2024-01-14',
    status: 'in_progress',
    amount: 79.99,
    description: 'Professional resume review and optimization',
    orderUrl: '/admin/services/SVC002'
  },
  {
    id: 'SVC003',
    buyerName: 'Michael Brown',
    buyerType: 'jobseeker',
    serviceName: 'Interview Preparation',
    serviceType: 'Career Services',
    orderDate: '2024-01-13',
    status: 'payment_pending',
    amount: 99.99,
    description: 'One-on-one interview coaching session',
    orderUrl: '/admin/services/SVC003'
  },
  {
    id: 'SVC004',
    buyerName: 'Emily Davis',
    buyerType: 'jobseeker',
    serviceName: 'LinkedIn Optimization',
    serviceType: 'Profile Enhancement',
    orderDate: '2024-01-12',
    status: 'completed',
    amount: 59.99,
    description: 'Professional LinkedIn profile optimization',
    orderUrl: '/admin/services/SVC004'
  },
  {
    id: 'SVC005',
    buyerName: 'David Wilson',
    buyerType: 'jobseeker',
    serviceName: 'Career Coaching Session',
    serviceType: 'Career Services',
    orderDate: '2024-01-11',
    status: 'active',
    amount: 149.99,
    description: '60-minute career guidance session',
    orderUrl: '/admin/services/SVC005'
  },
  {
    id: 'SVC006',
    buyerName: 'Lisa Anderson',
    buyerType: 'jobseeker',
    serviceName: 'Premium Job Alerts',
    serviceType: 'Job Search Tools',
    orderDate: '2024-01-10',
    status: 'in_progress',
    amount: 29.99,
    description: 'Advanced job matching and alerts',
    orderUrl: '/admin/services/SVC006'
  },

  // Employer Services
  {
    id: 'SVC007',
    buyerName: 'TechCorp Solutions',
    buyerType: 'employer',
    serviceName: 'Premium Job Posting',
    serviceType: 'Recruitment Services',
    orderDate: '2024-01-15',
    status: 'active',
    amount: 299.99,
    description: 'Enhanced job posting with priority placement',
    orderUrl: '/admin/services/SVC007'
  },
  {
    id: 'SVC008',
    buyerName: 'InnovateLabs',
    buyerType: 'employer',
    serviceName: 'Candidate Screening',
    serviceType: 'Recruitment Services',
    orderDate: '2024-01-14',
    status: 'in_progress',
    amount: 199.99,
    description: 'Professional candidate screening and shortlisting',
    orderUrl: '/admin/services/SVC008'
  },
  {
    id: 'SVC009',
    buyerName: 'Global Dynamics',
    buyerType: 'employer',
    serviceName: 'HR Analytics Report',
    serviceType: 'Analytics & Reporting',
    orderDate: '2024-01-13',
    status: 'payment_pending',
    amount: 399.99,
    description: 'Comprehensive HR analytics and insights',
    orderUrl: '/admin/services/SVC009'
  },
  {
    id: 'SVC010',
    buyerName: 'StartupHub',
    buyerType: 'employer',
    serviceName: 'Company Branding Package',
    serviceType: 'Branding Services',
    orderDate: '2024-01-12',
    status: 'completed',
    amount: 499.99,
    description: 'Complete employer branding and profile enhancement',
    orderUrl: '/admin/services/SVC010'
  },
  {
    id: 'SVC011',
    buyerName: 'Enterprise Systems',
    buyerType: 'employer',
    serviceName: 'Bulk Job Posting',
    serviceType: 'Recruitment Services',
    orderDate: '2024-01-11',
    status: 'active',
    amount: 799.99,
    description: 'Post up to 10 jobs with premium features',
    orderUrl: '/admin/services/SVC011'
  },
  {
    id: 'SVC012',
    buyerName: 'Digital Innovations',
    buyerType: 'employer',
    serviceName: 'Talent Pipeline Development',
    serviceType: 'Recruitment Services',
    orderDate: '2024-01-10',
    status: 'in_progress',
    amount: 599.99,
    description: 'Build and maintain a talent pipeline',
    orderUrl: '/admin/services/SVC012'
  },
  {
    id: 'SVC013',
    buyerName: 'FutureTech',
    buyerType: 'employer',
    serviceName: 'Employee Onboarding System',
    serviceType: 'HR Services',
    orderDate: '2024-01-09',
    status: 'payment_pending',
    amount: 899.99,
    description: 'Automated employee onboarding platform',
    orderUrl: '/admin/services/SVC013'
  },
  {
    id: 'SVC014',
    buyerName: 'CloudFirst',
    buyerType: 'employer',
    serviceName: 'Performance Management Tools',
    serviceType: 'HR Services',
    orderDate: '2024-01-08',
    status: 'completed',
    amount: 699.99,
    description: 'Employee performance tracking and management',
    orderUrl: '/admin/services/SVC014'
  },
  {
    id: 'SVC015',
    buyerName: 'DataDriven Inc',
    buyerType: 'employer',
    serviceName: 'Recruitment Analytics Dashboard',
    serviceType: 'Analytics & Reporting',
    orderDate: '2024-01-07',
    status: 'active',
    amount: 399.99,
    description: 'Real-time recruitment metrics and insights',
    orderUrl: '/admin/services/SVC015'
  }
];