/**
 * Current role / job title suggestions for the job seeker profile.
 * Users can also type any custom value.
 * Grouped by field to make the list easy to maintain.
 */
export const SUGGESTED_ROLES = [
  // Software & Engineering
  "Software Engineer",
  "Senior Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "iOS Developer",
  "Android Developer",
  "Web Developer",
  "WordPress Developer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Technical Lead",
  "Engineering Manager",
  "Solutions Architect",
  "Software Architect",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Platform Engineer",
  "Database Administrator",
  "QA Engineer",
  "Automation Test Engineer",
  "Manual Test Engineer",

  // Data & AI
  "Data Analyst",
  "Data Scientist",
  "Data Engineer",
  "Business Intelligence Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "Research Analyst",
  "Statistician",

  // IT & Security
  "IT Support Specialist",
  "IT Manager",
  "System Administrator",
  "Network Engineer",
  "Network Administrator",
  "Cybersecurity Analyst",
  "Information Security Engineer",
  "Help Desk Technician",
  "ERP Consultant",
  "SAP Consultant",
  "Salesforce Administrator",

  // Product, Project & Business
  "Product Manager",
  "Senior Product Manager",
  "Product Owner",
  "Project Manager",
  "Project Coordinator",
  "Program Manager",
  "Scrum Master",
  "Business Analyst",
  "Business Development Manager",
  "Business Development Executive",
  "Management Consultant",
  "Strategy Manager",
  "Operations Manager",
  "Operations Executive",
  "General Manager",
  "Country Manager",
  "Chief Executive Officer",
  "Chief Operating Officer",
  "Chief Technology Officer",
  "Chief Financial Officer",
  "Chief Marketing Officer",

  // Design & Creative
  "UI/UX Designer",
  "UX Researcher",
  "Product Designer",
  "Graphic Designer",
  "Senior Graphic Designer",
  "Motion Graphics Designer",
  "Video Editor",
  "Photographer",
  "Animator",
  "3D Artist",
  "Illustrator",
  "Art Director",
  "Creative Director",
  "Interior Designer",
  "Fashion Designer",

  // Marketing & Content
  "Marketing Manager",
  "Marketing Executive",
  "Digital Marketing Specialist",
  "Digital Marketing Manager",
  "SEO Specialist",
  "Performance Marketing Specialist",
  "Social Media Manager",
  "Social Media Executive",
  "Content Writer",
  "Copywriter",
  "Content Manager",
  "Brand Manager",
  "Public Relations Officer",
  "Communications Manager",
  "Event Manager",
  "Event Coordinator",
  "Influencer Marketing Manager",
  "Email Marketing Specialist",

  // Sales & Customer
  "Sales Executive",
  "Senior Sales Executive",
  "Sales Manager",
  "Sales Director",
  "Account Manager",
  "Key Account Manager",
  "Account Executive",
  "Inside Sales Representative",
  "Telesales Executive",
  "Retail Sales Associate",
  "Store Manager",
  "Assistant Store Manager",
  "Merchandiser",
  "Customer Service Representative",
  "Customer Service Manager",
  "Customer Success Manager",
  "Call Center Agent",
  "Relationship Manager",

  // Finance & Accounting
  "Accountant",
  "Senior Accountant",
  "Chief Accountant",
  "Accounts Payable Clerk",
  "Accounts Receivable Clerk",
  "Finance Manager",
  "Financial Analyst",
  "Financial Controller",
  "Auditor",
  "Internal Auditor",
  "Tax Consultant",
  "VAT Specialist",
  "Bookkeeper",
  "Payroll Officer",
  "Treasury Analyst",
  "Credit Analyst",
  "Investment Analyst",
  "Banker",
  "Relationship Officer",
  "Insurance Advisor",
  "Underwriter",
  "Claims Officer",
  "Actuary",

  // HR & Admin
  "HR Manager",
  "HR Executive",
  "HR Generalist",
  "HR Business Partner",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Recruitment Consultant",
  "Learning and Development Specialist",
  "Compensation and Benefits Specialist",
  "Payroll Administrator",
  "PRO (Public Relations Officer)",
  "Administrative Assistant",
  "Executive Assistant",
  "Personal Assistant",
  "Office Manager",
  "Receptionist",
  "Data Entry Operator",
  "Document Controller",
  "Secretary",

  // Supply Chain, Logistics & Procurement
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Logistics Manager",
  "Procurement Officer",
  "Procurement Manager",
  "Purchasing Officer",
  "Warehouse Supervisor",
  "Warehouse Assistant",
  "Inventory Controller",
  "Storekeeper",
  "Freight Forwarder",
  "Customs Clearance Officer",
  "Import Export Coordinator",
  "Delivery Driver",
  "Driver",
  "Fleet Supervisor",

  // Engineering & Construction
  "Civil Engineer",
  "Structural Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "MEP Engineer",
  "HVAC Engineer",
  "Chemical Engineer",
  "Industrial Engineer",
  "Petroleum Engineer",
  "Mining Engineer",
  "Architect",
  "Draughtsman",
  "Quantity Surveyor",
  "Site Engineer",
  "Site Supervisor",
  "Construction Manager",
  "Project Engineer",
  "Planning Engineer",
  "Safety Officer",
  "HSE Manager",
  "Quality Control Inspector",
  "Surveyor",
  "Foreman",
  "Technician",
  "Maintenance Technician",
  "Electrician",
  "Plumber",
  "Welder",
  "Carpenter",
  "Painter",
  "AC Technician",
  "Machine Operator",
  "Production Supervisor",
  "Production Manager",
  "Factory Worker",
  "CNC Operator",

  // Healthcare
  "Doctor",
  "General Practitioner",
  "Specialist Doctor",
  "Surgeon",
  "Dentist",
  "Nurse",
  "Staff Nurse",
  "Head Nurse",
  "Pharmacist",
  "Pharmacy Assistant",
  "Lab Technician",
  "Radiologist",
  "Radiographer",
  "Physiotherapist",
  "Occupational Therapist",
  "Nutritionist",
  "Dietitian",
  "Medical Representative",
  "Medical Coder",
  "Medical Insurance Coordinator",
  "Clinic Manager",
  "Caregiver",
  "Veterinarian",

  // Education
  "Teacher",
  "Primary School Teacher",
  "Secondary School Teacher",
  "Kindergarten Teacher",
  "Special Education Teacher",
  "Teaching Assistant",
  "Lecturer",
  "Professor",
  "Academic Coordinator",
  "School Principal",
  "Vice Principal",
  "Tutor",
  "Trainer",
  "Corporate Trainer",
  "Instructional Designer",
  "Librarian",
  "School Counselor",

  // Legal & Compliance
  "Lawyer",
  "Legal Advisor",
  "Legal Counsel",
  "Legal Secretary",
  "Paralegal",
  "Compliance Officer",
  "Contracts Administrator",
  "Company Secretary",
  "Risk Manager",
  "AML Analyst",

  // Hospitality, Travel & Food
  "Hotel Manager",
  "Front Office Manager",
  "Front Desk Agent",
  "Guest Relations Officer",
  "Housekeeping Supervisor",
  "Housekeeping Attendant",
  "Restaurant Manager",
  "Chef",
  "Executive Chef",
  "Sous Chef",
  "Commis Chef",
  "Cook",
  "Baker",
  "Pastry Chef",
  "Waiter",
  "Waitress",
  "Barista",
  "Bartender",
  "Cashier",
  "Travel Consultant",
  "Travel Agent",
  "Tour Guide",
  "Reservations Agent",
  "Flight Attendant",
  "Pilot",
  "Airport Ground Staff",

  // Real Estate & Facilities
  "Real Estate Agent",
  "Property Consultant",
  "Property Manager",
  "Leasing Executive",
  "Facilities Manager",
  "Facility Coordinator",
  "Building Supervisor",
  "Security Officer",
  "Security Supervisor",
  "Cleaner",
  "Gardener",

  // Media & Others
  "Journalist",
  "Editor",
  "Translator",
  "Interpreter",
  "Sound Engineer",
  "Radio Presenter",
  "Fitness Trainer",
  "Yoga Instructor",
  "Beautician",
  "Hair Stylist",
  "Makeup Artist",
  "Spa Therapist",
  "Tailor",
  "Social Worker",
  "Intern",
  "Fresh Graduate",
  "Freelancer",
] as const
